### ISSUE TITLE
Can't walk across the bridge

### ISSUE THREAD

**Issue by pcbeard** [Phazorknight/Cogito#12]
On main (1891d69), I noticed that if you lower the ramp by pressing and holding, you can no longer cross the bridge (without jumping); the lip seems to cause a hitch. Possibly caused by the stair climbing code? Here's a screen shot:

![Screenshot 2024-01-04 093723](https://github.com/Phazorknight/Cogito/assets/793781/295ff35d-9dce-460f-8435-88b4a34c78c6)

**Comment by Phazorknight** [comment]
Thanks for flagging this issue.
You are correct with your assumption that the stair climbing code is causing this.
I've found the issue and (hopefully) fixed it in beta 202401.3.

There's now a step slope angle attribute that should help with this. I set this to 1 instead of 0 and it fixed the issue with the ramp.

**Comment by pcbeard** [comment]
Looking forward to reading your new stair climbing code.
