### ISSUE TITLE
Current Slot: C

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#127]
No matter which save slot I choose on the main menu, the save slot is always set as C

**Comment by Phazorknight** [comment]
Looking into this...

**Comment by Phazorknight** [comment]
Could you please give https://github.com/Phazorknight/Cogito/commit/600c7ba5a2178b4aee6794f36c72ceee87007a90 a try?

Basically the issue was that when starting a new game, the CogitoSceneManager wasn't switched to the corresponding save slot. Now the save slot buttons need to be given a "manual save slot name". This is the save that will be looked for when the menu loads, and if it doesn't exist, it shows up a s "new game" slot and a save by that name will be created on starting it and then saving.
Defaults are named A, B and C, so if any of those exist, they should already show up.
