### ISSUE TITLE
Godot Asset Lib commit mistake. You've linked to an old Jan 24 commit (b09ac18) not your most current one Mar 26 (10befee) (5 hours ago at time of writing).

### ISSUE THREAD

**Issue by BurntAussieTyre** [Phazorknight/Cogito#129]

**Comment by Phazorknight** [comment]
Godot Asset lib is approved by mods and thus always a bit delayed/behind with what it links to.

As COGITO is still in active development and new commits are pushed regularly, I recommend just following the link to the Github repo. I've also added a hint to do this in the Asset Library description.

Closing this with "wontfix" as it's not a COGITO issue, rather than just the nature of how the Godot Asset Library is updated, etc.
