### ISSUE TITLE
Window size resets after scene change

### ISSUE THREAD

**Issue by brian-holsters** [Phazorknight/Cogito#154]
When playing in windowed mode you can resize the window (this is a great feature which i love using since i have a weird resolution monitor, so please dont fix by removing xD), however whenever a scene change happens, the window resizes back to the saved resolution in the configuration (which makes sense i guess).

Possible solutions:
- completely ignore resolution on scene loading, i haven't really looked into what exactly is causing this to happen, so i don't know if this is possible...
- save resolution to the settings automatically on window resize, this one is probably the easier way to solve the issue, and would also ensure the game opens with the same resolution as last execution.

**Comment by Phazorknight** [comment]
So the Window resize on scene change happens due to the options cfg being loaded whenever the OptionsMenu being loaded (this is to make sure the game loads with the same setting whenever you start it).

Hearing your specific issue, i think the ideal solution would be something like this:
- In the Options menu: a "custom" selection to the resolution drop down.
- When "custom" is selected / when custom is selected and "apply" is pressed, Godot detects the current window size and saves this value as the resolution instead of one of the presets.
- Thus, whenever the scene changes, the resoultions "sticks".

This would require some changes to the options script, but should be doable.
