### ISSUE TITLE
A character flies a crate

### ISSUE THREAD

**Issue by Oldos4** [Phazorknight/Cogito#208]
**Cogito and Godot Engine Version:**
Cogito BETA 202401.13 
Godot v4.2.2.stable.official [15073afe3]

**Description:**
If you stand on the crate, press the "Carry" button and start moving the mouse - the character starts moving with the crate at high speed. If you become skilled and ride the crate, you can even fly up on it like Aladdin
**Reproduction steps:**
1. Stand on the crate
2. Press the "Carry" button
3. Start moving the mouse

**Expected behavior:**
I expected the crate to not move under the weight of the character

**Screenshots:**
https://www.youtube.com/watch?v=RyKwsWDjpWE

**Comment by Phazorknight** [comment]
Hi Oldos,

This is a legacy bug. We've reworked how carrying of objects works in the meantime, so please download the latest version of COGITO from GitHub here and this should be better.

**Comment by Oldos4** [comment]
Hey, still can do it with some objects
https://youtu.be/hDCx5fVcb1Q

**Comment by PeterD23** [comment]
Propflying is inevitable in every 3D FPS project with physics objects

**Comment by Phazorknight** [comment]
@Oldos4 this behaviour is from physics forces applied to the carryable object. Basically as you carry an object it's being pulled towards the carry position. If the player is in it's way, the player gets "pushed".

You can reduce this by lowering the `carrying velocity multiplier` in the CarryableComponent, and also reduce the carry distance, so the object doesn't get pulled so far/strong.

Otherwise, this isn't 100% avoidable with vanilla Godot physics, 99% of these issues are physics / collider settings/issues.

**Comment by Phazorknight** [comment]
Closing.
