### ISSUE TITLE
The platform pushes the player off the map if you stand under it

### ISSUE THREAD

**Issue by Oldos4** [Phazorknight/Cogito#210]
**Cogito and Godot Engine Version:**
Cogito beta 202405.16
Godot 4.2.2

**Description:**
The platform pushes the player off the map if you stand under it

**Reproduction steps:**
1. Raise the platform
2. Stand under it
3. Lower the platform

**Expected behavior:**
I expected the platform to do damage or push the player to the side

**Screenshots:**
https://youtu.be/Pp1rdnV7Irg

**Comment by Phazorknight** [comment]
Yeah, classic issue of what happens when a collider gets caught between two other colliders, that's an issue in pretty much any engine and it's a bit subjective as to what one expect to happen.

If you make the floor collider thicker, the player will then instead glitch through the platform ending up on top of it.

The expected behaviour/solution to this would be one of these options:

- Put a collider underneath the platform so the player can't enter this area.

- Make the platform "deadly" to be under, by putting a hazardzone underneath it and setting it to a very high drain rate (>100)
![image](https://github.com/Phazorknight/Cogito/assets/70389309/1fef9aa8-65b8-4fd8-9fc7-631c23492624)

**Comment by Oldos4** [comment]
Thank you! Both options seems cool

**Comment by Phazorknight** [comment]
Options where provided on how to remedy this issue, so I'm gonna close this.
