### ISSUE TITLE
Multiple interactions can occur with a single button press

### ISSUE THREAD

**Issue by BryceBarbara** [Phazorknight/Cogito#214]
**Cogito and Godot Engine Version:**
beta 202406.01 with Godot v4.3.beta1.mono.official [a4f2ea91a]

**Description:**
If you are carrying an object and looking at an interactable thing, pressing "interact" will result in both the object being dropped and the interactable being activated. Although the interaction hint says "Drop", both things happen.

**Reproduction steps:**
1. Pick up an object
2. Look at a door
3. See the interaction hint say "Drop"
4. Press Interact (F by default)
5. See the object drop as well as the door activate

**Expected behavior:**
Only the object drops.

**Screenshots:**

https://github.com/Phazorknight/Cogito/assets/24460210/3eb913da-53d9-49f2-9f57-8fa89860b8f7

**Comment by Phazorknight** [comment]
Hey, can you please double check that you're running the latest version of COGITO?

The UI in the video you posted looks like it's from an older version.
I've tried to reproduce the video in the current version and the bug did not occur.

**Comment by BryceBarbara** [comment]
Sure thing, I can do that later tonight. I had created the project yesterday via Godot's own asset manager thing and used the Cogito template but maybe that uses an out-of-date thing somehow?

**Comment by Phazorknight** [comment]
Yeah, the version that's on the AssetLibrary has to be manually updated by me and then manually approved by a Godot Mod. Since I don't want to flood them with minor updates, I usually hold off to update it until more major releases. That's why I currently try to point everyone to the GitHub instead.

It's been quite a while though, so I should probably update the AssetLib version soon. 😅 

Another reason is that COGITO works better as a whole project instead of an addon.

**Comment by BryceBarbara** [comment]
Thank you for explaining that! I just pulled down the latest version and things work a lot better! The inverted y-axis at the start always throws me off but at least the multiple interaction bug has been resolved! 😊
