### ISSUE TITLE
"CogitoSceneManager" not declared in the current scope

### ISSUE THREAD

**Issue by ZiggyCastillo** [Phazorknight/Cogito#243]
Error appears in cogito_player.gd file.

"Line 179:Identifier "CogitoSceneManager" not declared in the current scope.
Line 220:Identifier "Audio" not declared in the current scope.
Line 602:Identifier "Audio" not declared in the current scope."

Due to this error, I am unable to test or try anything out, as the scene refuses to play untill these errors are fixed

**Comment by Phazorknight** [comment]
How did you install Cogito?
This looks like you don't have the Plug-Ins/Autoloads configured in your project.

We strongly recommend making a copy of the COGITO project and use that as your base instead of copying it into your existing project. You can also see the documentation here for more info: https://cogito.readthedocs.io/en/latest/gettingstarted.html

**Comment by ZiggyCastillo** [comment]
Alright, I setup a new project and it worked. Althought whenever I make a new scene and setup the player, he keeps falling through the floor regardless of my collisions. Im pretty new to Godot so idk if its something simple that im missing or if its an actual issue that im having. Heres my scene setup
![image](https://github.com/user-attachments/assets/ec741963-7eb1-4de0-a2c5-2a0054cac1ac)

**Comment by Phazorknight** [comment]
Hm... hard to say from just this.

Instead of the packed scene `floorFull`, could you do just a MeshInstance of a box or something? (Just to rule out stuff that might be inside that scene.

And could you also add some generic RigidBody3D object to see if that can collide with your floor just fine?

Just to rule out a few settings first.
Also could you add the `cogito_scene.gd` script to your level scene root node? (just called `Node3D` in your screen shot). This is needed for some Cogito functions to behave correctly (though should not cause the player to just drop through floors)

**Comment by Phazorknight** [comment]
Closed due to inactivity. Feel free to reopen.
