### ISSUE TITLE
After placing item and saving, snap shape reset to visible on load

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#298]
**Cogito and Godot Engine Version:**
Godot: 4.2.2
Cogito: beta 202409.04

**Description:**
The snap slot snap shape reappears after placing the item, saving and then reloading.

**Reproduction steps:**
1. Place item into snap slot
2. Save
3. Load

**Expected behavior:**
The snap shape doesn't reappear on a saved active snap slot on load

**Fix:**
Change line 186 in `cogito_snap_slot set_state():`
```
if snap_shape:
	snap_shape.visible = is_active
```
to this:
```
if snap_shape:
	snap_shape.visible = !is_active
```

**Comment by Phazorknight** [comment]
Thanks for flagging this. Your fix isn't quite correct, as the `is_active` property is not meant for this. Instead it is meant to control if the snap_slot is able to accept objects in general or not.

I've found the issue, though, the `is_holding_object` property wasn't saved. As this also controls the snap_shape visibility, adding this to the saved properties fixes the issue. Will push in the next update.

**Comment by OvercastInteractive** [comment]
Ok, thanks for the explanation. I'm glad it wasn't too much trouble to fix this.

**Comment by Phazorknight** [comment]
I've just added this in https://github.com/Phazorknight/Cogito/commit/a3e6064ad016a27b435229b6e9086c91bbe8df61

There's still an issue when using snap_shape with an InventoryItem: On load the reference to the spawned item gets lost. Due this, the snap_slot `is_holding_object` status doesn't get flipped back to `false` when taking the item out of it.

Will try a bit if I can find a fix for this, otherwise I might remove the `InventoryItem` functionality of the snap_slot and refer people to use the `Cogito_Switch` instead as it's used in the Legacy Demo scene.
