### ISSUE TITLE
Doors ignore local scene tranforms

### ISSUE THREAD

**Issue by Bezoika** [Phazorknight/Cogito#30]
Been really struggling with doors, if the door's local rotation is set differently than the packed scene rotation, it will reset to the packed scene rotation on scene load. This happens whether it is Tween or Animation based.

**Comment by Bezoika** [comment]
Interestingly enough, if i tie the instanced door to a Node3D and set the rotation on that locally instead of on the door, this is no longer an issue.

**Comment by Phazorknight** [comment]
Hi,
I understand your issue and I've struggled with this myself. Technically it's happening because the doors **don't** ignore the transforms, but it's still not intuitive.
The easiest way to solve this would be to reparent the Node you attach the door script to (usually an Animateable Body) to the packed scene root node, instead of it itself being the root node.

I'm hoping to have some time to update the documentation soon to show this step by step.

**Comment by Bezoika** [comment]
I see now, I was confusing myself thinking it had to do with save states or some weird function in the doors script. I'll just have to make sure my door scenes have an extra parent node.
