### ISSUE TITLE
Inventory Item can be dropped through walls & doors

### ISSUE THREAD

**Issue by niefia** [Phazorknight/Cogito#300]
**Cogito and Godot Engine Version:**
4.2.2

**Description:**

Inventory Item can be dropped through walls, and doors.
Could be a particular issue for important items such as keys

**Reproduction steps:**
1. Pick up key from CEO office window
2. Open inventory while facing CEO office door
3. Drop key behind CEO office door
4. Key is now unobtainable

**Expected behavior:**
Raycast collision should be run before dropping to check for valid drop locations and avoid dropping items through walls

**Comment by Phazorknight** [comment]
Thanks for this!
The way I did the collision check for this was wrong. I just pushed a fix in https://github.com/Phazorknight/Cogito/commit/a3e6064ad016a27b435229b6e9086c91bbe8df61, so please take a look!

**Comment by niefia** [comment]
Gave it a test and seems to have fixed it for walls, and doors for larger objects. But it's still possible for small objects like the Key to clip through doors

**Comment by niefia** [comment]
I agree with you that it's definitely more a collisions issue than one with how objects are spawned here, and the fix does work entirely as intended.

Could just make the key undroppable, or make it larger to prevent any collision issues for this case

**Comment by OvercastInteractive** [comment]
This type of unwanted physics behavior is usually fixable by inflating the margin property of collision shapes and using interpolation (which probably won't be available until Godot 4.4 releases 😟).

Otherwise, before dropping an item a drop-specific Shapecast or Area3D can check if there's enough space out from camera center (for gamepad) and out from viewport mouse position (for mouse, keyboard) to ensure there's vacant space to drop the item. To take it further you could also shoot a downward ray from the center of the drop point to ensure there's a surface to drop it on. If there's no room or valid surface (you can't drop the item over lava or something) the drop can be canceled, and an interaction prompt can read "Cannot drop (item name) here".

An alternative solution would be more extensive and involve checking for vacant spaces in increments around the camera (12 o'clock, 1 o'clock, 2 o'clock...) and dropping the item at the first vacant space.

Echoing what's already been said, important items should probably always be undroppable anyway. In any case, dropping should feel reliable and not ever concern the player, which would be the case if the failure rate rises above 10% of the time (what if I can't pick the item I drop back up?!).

I can test this out on my end and see if the results are more in line with expected behavior.

What do you think @Phazorknight, @niefia?

**Comment by Phazorknight** [comment]
> unwanted physics behavior is usually fixable by inflating the margin property

oh that's good to know, I've struggled with these behaviors for quite some time now.

> before dropping an item a drop-specific Shapecast or Area3D can check if there's enough space out from camera center (for gamepad) and out from viewport mouse position (for mouse, keyboard) to ensure there's vacant space to drop the item. To take it further you could also shoot a downward ray from the center of the drop point to ensure there's a surface to drop it on. If there's no room or valid surface (you can't drop the item over lava or something) the drop can be canceled, and an interaction prompt can read "Cannot drop (item name) here".

@OvercastInteractive this sounds great to me and should really suffice. I'd probably only do the camera center check (or use the interaction_raycast tip as the drop/spawn location and then adjust as needed based on item size.

I don't think we need any additional vacant space check.

> dropping should feel reliable and not ever concern the player

fully agree, having issues appear when dropping would erode player/developer trust, so want to avoid that.

Any tweaks/additions to this are welcome.

**Comment by niefia** [comment]
All sounds like good ideas.

> An alternative solution would be more extensive and involve checking for vacant spaces in increments around the camera (12 o'clock, 1 o'clock, 2 o'clock...) and dropping the item at the first vacant space.

For this we could instead repurpose the Navmesh safe location finder I introduced in with the Sittables for determining safe item location placement, since Navmesh should also give a sensible approximation of where the player can access.

**Comment by Phazorknight** [comment]
Closing this as inital issue has been resolved.
