### ISSUE TITLE
Possible to slide through Laboratory windows due to step check behaviour

### ISSUE THREAD

**Issue by niefia** [Phazorknight/Cogito#305]
**Cogito and Godot Engine Version:**
Godot version: 4.2.2
Cogito version: beta 202409.04

**Description:**
Possible to slide through Laboratory windows due to step check behaviour

**Reproduction steps:**
1. Run at the Windows in the Laboratory
2. Should enter the windows, due to step check registering them as step
3. Also enters slide as player forced into crouch, whilst running

**Expected behavior:**
Not sliding through windows.
Can be fixed by lowering default step height

**Screenshots:**
The type of window: ![windows](https://github.com/user-attachments/assets/6fd69639-753c-45bb-84a6-85cf8c5e3976)

**Comment by OvercastInteractive** [comment]
I would also like to add that because this template supports auto-crouching, crouch jumping, stepped-geometry stairways and the like that there should be some guidelines for things like window height from the ground, stair step and table height.

I also think lowering the default step height a little would feel more accurate, because you can too easily walk up onto the coffee table in the lobby, and at the same time it should retain the smooth movement and capabilities of walking over ledges and grounded objects easily that come with a higher step height.

Because the feature is quite dynamic it might just be a matter of having some basic guidelines for minimum window and table height, otherwise it would just require lots of testing and iteration to fix all the exploits, which is expected regardless. 😭

**Comment by mrezai** [comment]
I found what cause this problem:

This line is related to stair stepping:
https://github.com/Phazorknight/Cogito/blob/4c1df66d938d5ae3dbec67cf14546c0a54332fd9/addons/cogito/CogitoObjects/cogito_player.gd#L1082
and after this head's position change, in next frame, condition in this line will be true:
https://github.com/Phazorknight/Cogito/blob/4c1df66d938d5ae3dbec67cf14546c0a54332fd9/addons/cogito/CogitoObjects/cogito_player.gd#L877
and in the next frame this part of code will be executed because raycast is_colliding is true:
https://github.com/Phazorknight/Cogito/blob/4c1df66d938d5ae3dbec67cf14546c0a54332fd9/addons/cogito/CogitoObjects/cogito_player.gd#L853

Before:

https://github.com/user-attachments/assets/98b3fcab-7155-44fd-9b39-f2b7ce2e180f

After replacing these two lines of code with ```pass```, issue will be solved but we need a better solution!
https://github.com/Phazorknight/Cogito/blob/4c1df66d938d5ae3dbec67cf14546c0a54332fd9/addons/cogito/CogitoObjects/cogito_player.gd#L879-L880


https://github.com/user-attachments/assets/5755706d-e409-40aa-919a-1c55e294a1a5


These lines added by @Phazorknight in this commit: https://github.com/Phazorknight/Cogito/commit/71fcf4c14104136af527a1a961c5a8ea2a4b1994
I think someone with better understanding of player's code can fix this bug without introducing new one!
I found another bug related to crouch/uncrouch and stair stepping, I'll send a PR for that soon.

**Comment by Phazorknight** [comment]
Thanks everyone for flagging this and investigating.

For now, I've simply reduced the step height in the stair settings of the player controller (it was `0.5` i set it to `0.35` ) and that seems to do the trick. (see https://github.com/Phazorknight/Cogito/commit/97d53f1544a503623b1a192b24d7be003dbee161 )
 This also helps with avoiding the player climbing on top of tables and couches in the Lobby scene.
It's still possible to jump-crouch through the Lab windows, which I think is fine. It seems like the kind of opening in a wall the player should be able to climb through.

**Comment by Phazorknight** [comment]
Closing this as original issue has been resolved.
