### ISSUE TITLE
Load from Main Menu

### ISSUE THREAD

**Issue by ac-arcana** [Phazorknight/Cogito#99]
Once there is a player save, a load button could show up on the main menu.

**Comment by ac-arcana** [comment]
I also note there is no options on the main menu. I thought this was present before?

**Comment by Phazorknight** [comment]
There was, but when we reworked the pause menu and added new options, it broke the old menu, so I removed that from the Main menu scene as it would otherwise break. Sorry about that! 

I have a plan to redesign the main menu with working options and multiple save slots, will hopefully get to it in the next week.

**Comment by ac-arcana** [comment]
Your new main menu is looking great!
The major thing I'll note is that it does not scale with resolution. It does fit on the smallest resolution I can select though, so I suppose this isn't necessarily an issue.
Do you have further plans for this?

**Comment by Phazorknight** [comment]
Thanks! Yeah, I'm still tinkering with it a bit.
I don't think the current implementation of the options menu is ideal as it's now split up between two scenes which would make adding new options a hassle.
The way options are applied is not consistent between the main menu and the pause menu either, so that can cause issues like the one you mentioned.

I will probably create a single options scene again that can be used for both the pause and the main menu, with opening/closing it being used to apply settings, but will have to test this with some trial and error.

**Comment by Phazorknight** [comment]
Okay, I pushed another small update that re-shuffles the menu structure a bit again in https://github.com/Phazorknight/Cogito/commit/b872a285b6336c777d3013edacafb868a6c6b6be

This now creates a single PackagedScene for the options menu which should make updates to it more streamlined and easier.

@ac-arcana , if this works for you, I'd consider the "load from main menu" issue closed. For the funkyness with the resolutions and window modes, I'll continue to update in #120 .

**Comment by ac-arcana** [comment]
Yes, loading from the main menu is working an the options are all there. This issue is resolved
